### PR TITLE
Import TMX files (mergeable)

### PR DESCRIPTION
**Pull request by victorlevasseur**
#213 merged into master (no real conflicts, don't know why Github shown that there are some).

### CODE REVIEW

**Comment by victorlevasseur** [comment]
It seems that it's doesn't build (with GD_IDE_ONLY) because of the changes in ResourcesManager.

**Comment by victorlevasseur** [comment]
Fixed now.

**Comment by 4ian** [comment]
Cool! Will merge it soon if the build passes :)

**Comment by victorlevasseur** [comment]
The build is not passing on Travis CI with gcc because the download of SFML was stopped by the server.

**Comment by 4ian** [comment]
I've merged it :) Good job! :+1:

**Pull request merged**
