### PR TITLE
Use TDM-GCC 4.9.2 (windows), wxWidgets 3.0.2 on Windows, enable C++11, remove Boost

### PR DESCRIPTION
**Pull request by victorlevasseur**
- use TDM-GCC 4.9.2 on Windows : (better) C++11 support, can compile with 4 threads to reduce compilation duration (can't achieve that with 4.5.2)
 - wxWidgets 3.0.2 on Windows
 - enable C++11 to use std::unordered_set/map and std::shared/weak_ptr instead of their Boost equivalent.
 - remove Boost (and add a function to put a string to uppercase)

Save more than 60 Mo for the end user (boost headers) and 400 Mo for a dev (boost folder)

TDM-GCC 4.9.2 : http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/tdm-gcc-4.9.2.exe/download
wxWidgets 3.0.2 for Windows : https://www.mediafire.com/folder/f34xy126y11i4/GDevelop

This PR still need testing (I've already made some tests, everything should be working fine) and we need to find a way to remove the libPNG warnings (bash script ?). 
Article about how to remove ICCP profile from PNG : http://www.app-v.be/citrix/how-to-remove-icc-profile-information-from-png-images-from-web-interface

### CODE REVIEW

**Comment by 4ian** [comment]
Awesome! :+1:  Thanks for this nice work! I'll take a look at it tomorrow and merge it :smiley:  (probably in a separate branch but I'll integrate it then into master quickly if everything is ok!).

**Comment by victorlevasseur** [comment]
By the way, if you want to rebuild wxWidgets yourself : it may fail saying that an object file is missing (don't remember its name, but it ends with ctlg.o). If this is the case, just find the almost identical file (with ct**r**lg.o at the end) and rename it. I've saw some other projects having the same problem with wxWidgets 3.0 on Windows.

**Comment by 4ian** [comment]
Merged in ``c++11`` branch. So far everythings seems ok on my Ubuntu 14.04 :+1: 
I'm going to test it on Windows. Thanks for the info concerning wxWidgets :smile:

**Comment by victorlevasseur** [comment]
Have a strange problem when compiling on Windows.
The compilation of PlayWin.exe fails because AutomatismsRuntimeSharedDataHolder::operator=() is not defined (normal because it doesn't have GD_EXTENSION_API in front of the class name). I can't find where this operator can be called from PlayWin.exe.

**Comment by 4ian** [comment]
Did you update the MinGW32 directory with TDM-GCC 4.9.2?

**Comment by victorlevasseur** [comment]
It happens when building GD, not when using it ;)

**Comment by victorlevasseur** [comment]
Works fine if I add GD_API to AutomastismsRuntimeSharedDataHolder.

**Comment by 4ian** [comment]
You should have a slightly outdated working directory because GD_API is already added to AutomatismsRuntimeSharedDataHolder ;)

**Comment by victorlevasseur** [comment]
Yeah, I've noticed that on the c++11 branch (was using remove-boost branch from my repo).

**Comment by 4ian** [comment]
I've updated all the PNG files using imagemagick to strip useless chunks, could you try the latest commit? :) (It was a pain to do, because it strip some png to 8bit files which are not supported by SFML. I had to restore the old png) I've still some warnings while opening the scene editor :/
And the latest windows look&feel is not working anymore even if there is the .Manifest file, it's strange..

Finally, I've updated the ``copyWindowsLibraries.bat`` file to also copy SFML dependencies and wxwidgets dll. Could you try to remove all dlls and launch a compilation to trigger the execution of this script? Let me know if any dll is missing.

**Comment by victorlevasseur** [comment]
You could have used pngcrush which doesn't break pictures for SFML. But I still get the same warning when opening the scene editor only.

For the L&F, there are no problems for me, GDevelop looks like before. :S

**Comment by victorlevasseur** [comment]
You should add ```wxDisableAsserts();``` at the beginning of the application initialization to avoid an assertion about the locale (only happening on Windows with wxWidgets 3.0).

**Comment by 4ian** [comment]
C++11 branch is now merged into master. I didn't add ``wxDisableAsserts();`` though, could you add it by yourself if necessary?

**Pull request merged**
