### PR TITLE
Raycast condition

### PR DESCRIPTION
**Pull request by Lizard-13**
I guess it's ok now, I can't test it because a compilation error from IDE/resource.rc, though :/ ... please test it before :P

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for the new PR :)
What's the error with IDE/resource.rc? You may want to delete the build folder that was created with CMake and start again the setup with CMake, so that everything is re-built from scratch ;)

**Comment by Lizard-13** [comment]
> You may want to delete the build folder that was created with CMake and start again the setup with CMake

I have already done that... twice. Now I've deleted the entire repo and cloned it again, but I get the same error:
```
C:\MinGW32\bin\windres.exe: C:\\Users\\Maciel\\Programacion\\gits\\GD\\IDE\\resource.rc:13: syntax error
IDE\CMakeFiles\GDIDE.dir\build.make:936: recipe for target 'IDE/CMakeFiles/GDIDE.dir/resource.rc.obj' failed
```
Already tried changing the file encoding to ANSI/UTF-8/UTF-16. I don't know, maybe I've to reinstall windres :/
It works if I delete the lines 13 and 14 (FILEVERSION and PRODUCTVERSION).

Did you manage to try the raycast?, there is a test game in the GDJS/tests/games to ensure everything is ok 😄

**Comment by 4ian** [comment]
Tested it successfully the HTML5 version on macOS! :) 👍  I still have to test the native version.
This condition will be really useful! For example, to do line-of-sight for enemies or things like that :)

Can you paste here the content of resource.rc? Looks like it was not generated properly, we can surely fix this.

**Comment by Lizard-13** [comment]
Great!

Here is the file content:
```
aaaa ICON "icon.ico"

#include "GDCore/Tools/VersionPriv.h"
#include "wx/msw/wx.rc"

#ifndef DEBUG
#define VER_DEBUG                   0
#else
#define VER_DEBUG                   VS_FF_DEBUG
#endif

1 VERSIONINFO
FILEVERSION    	GD_VERSION_RC
PRODUCTVERSION 	GD_VERSION_RC
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904E4"
        BEGIN
            VALUE "CompanyName",      "Florian Rival"
            VALUE "FileDescription",  "GDevelop Integrated Development Environment"
            VALUE "FileVersion",      GD_VERSION_RC_STRING
            VALUE "InternalName",     "GDevelop IDE"
            VALUE "LegalCopyright",   "2008-2016 Florian Rival"
            VALUE "LegalTrademarks1", ""
            VALUE "LegalTrademarks2", ""
            VALUE "OriginalFilename", "GDIDE.exe"
            VALUE "ProductName",      "GDevelop"
            VALUE "ProductVersion",   GD_VERSION_RC_STRING
        END
    END

    BLOCK "VarFileInfo"
    BEGIN
        /* The following line should only be modified for localized versions.     */
        /* It consists of any number of WORD,WORD pairs, with each pair           */
        /* describing a language,codepage combination supported by the file.      */
        /*                                                                        */
        /* For example, a file might have values "0x409,1252" indicating that it  */
        /* supports English language (0x409) in the Windows ANSI codepage (1252). */

        VALUE "Translation", 0x409, 1252

    END
END
```

**Comment by 4ian** [comment]
Can you paste here the content of `Core/GDCore/Tools/VersionPriv.h`?

**Comment by Lizard-13** [comment]
```
#define GD_VERSION_STRING "4.0.96"
#define GD_VERSION_RC 4.0.96
#define GD_VERSION_RC_STRING "4.0.96\0"
#define GD_DATE_STRING __DATE__
```

**Comment by 4ian** [comment]
I have the same content :/ I don't understand why you would get a syntax error in this case? 😕

**Comment by Lizard-13** [comment]
Docs says that VERSIONINFO should be like 4,0,0,96 (4 16-bit integers separated by commas), I'm trying to recompile with this change

**Comment by Lizard-13** [comment]
Yup, after editing VersionPriv.h and changing the generated line:
`#define GD_VERSION_RC 4.0.96`
into:
`#define GD_VERSION_RC 4,0,96,0`
it compiled, and seems to work fine :footprints: :mag_right:

**Comment by 4ian** [comment]
Interesting! According to GenerateVersionFull.cmake and GenerateVersionLazy.cmake, comma should indeed be generated by CMake!
Not sure why it's not the case, but it may be related to a commit that I did to pin the version number and don't read it from latest git tag (https://github.com/4ian/GD/commit/b261faacfcc18d8971066aa8568bf7ab5c2c3d7e).

**Comment by Lizard-13** [comment]
Yes, the version string is fixed to "x.y.zw" and FULL_VERSION_NUMBER is required, in the full version generator there is no match for the regex "x.y.zw-e-.*"... it seems... I've never learned regex (but it's in my TODO).
Anyway I guess you already know what to do :)

**Comment by 4ian** [comment]
When developing, you can disable full number version as it's no useful and will trigger recompilation of lots of files each time :)
Anyway, I'm going to merge this tomorrow so that it's in the next version of GD5 (that will be released tomorrow too I think) :)

Also let me know your GDevelop 5 account email so that I can give you a free Pro subscription ;)

**Pull request merged**
