### PR TITLE
Add a build and run Windows batch script in /scripts folder

### PR DESCRIPTION
**Pull request by blurymind**
I've been using this simple batch script to automate all the install and run steps to get the electron editor up and running. Perhaps it can save others some time- especially those who like running the bleeding edge version

### CODE REVIEW

**Comment by blurymind** [comment]
not sure if that is the right folder, chose it based on where other batch scripts are :)

**Comment by 4ian** [comment]
Sounds cool, let me double check that this afternoon/evening :)

**Comment by 4ian** [comment]
I think we can add it, it can be useful :)
Can you add a echo command to tell that if an error occurs, the user should check if git and node are properly installed?

Something like:
```bat
echo This will install the dependencies and launch GDevelop development version. Please make sure you have git and Node.js installed.
```

Also there are good chance that this script is launch after the person cloned the git or at least downloaded the archive of the git I think?
My Batch programming is a bit rusty, but I'm pretty sure you could detect if some directory is existing (for example, `..\newIDE`) and if yes, skip the clone, change the working directory to here and proceed with the npm install :)

Let me know at least when you have to `echo` added and we can proceed.
You can also add a description line in the README in https://github.com/4ian/GD/tree/master/scripts

Thanks for sharing this! 👍

**Comment by blurymind** [comment]
Thank you for the feedback :)

On the script - it shows the comments about requiring nodejs to be installed in the console when you run it.
Since it also includes git cloning gdevelop, the script is not designed to be used after gdevelop has already be cloned - but I can add that to it

If you run it twice, it does detect that the GD folder already exists and git skips cloning it again. If there are any errors in the build process - CMD will show them to the user - there is no need to write extra lines for that

**Comment by 4ian** [comment]
Thanks for the update :) 
Should the `@echo off` be put on the top to avoid REM comments being displayed?

Will be ok to merge then I think :)

**Comment by blurymind** [comment]
done and tested :)

**Comment by 4ian** [comment]
Thanks! Merged 😄

**Pull request merged**
