### PR TITLE
Introduce gd::FileStream

### PR DESCRIPTION
**Pull request by victorlevasseur**
What is this new class ?
===
This class is an equivalent of ```std::fstream``` (and can also replace ```std::[io]fstream```) but it allows to load a file from a path as a ```gd::String```.

On Linux/Mac OS, this is a simple wrapper:
```c++
gd::String filepath = "some weird characters here.txt";

//You can do this:
gd::FileStream f(filepath); // or f.open(filepath);
//Instead of:
std::fstream f(filepath.ToLocale());
```

Why ?
===
But, the class is the most useful on Windows as the libstd implementation of ```std::[io]?fstream``` is only able to open file with an ASCII filename (no support for ```std::wstring``` filepaths).

On Windows, ```gd::FileStream``` can open a file with **non ASCII filepaths** (given that the path is still obviously supported by Windows itself and its weird ~~UTF-16~~ UCS-2 encoding)

How ?
===
```gd::FileStream``` uses a MinGW extension that allows to open a file from a C ```FILE*``` descriptor. Luckily enough, MinGW provides a Microsoft extension that allows to open a C ```FILE*``` descriptor from a wide path (```wchar_t*```). The class manages the file descriptor and a filebuffer that makes the link between the ```std::iostream``` (```gd::FileStream``` as ```std::fstream``` inherits from ```iostream```).

On Linux, the class directly opens a ```std::filebuf``` and link it to the base ```std::iostream```. As the filesystem encoding is considered to follow the locale, the ```gd::String``` is converted into the current locale (often ```UTF-8``` these days) before opening the file.

Tests
===

Tests have been added to test the critical parts of the class (the browsing, reading, writing operations are managed by the ```std::iostream```` so no need to test them. Only the opening/closing and states are tested).

Bonus Nb.1
===

This PR also implements a ```gd::SFMLFileStream``` that allows SFML resources can be loaded from files like this:

```cpp
gd::SFMLFileStream stream;
stream.open("aaaa.png");

sf::Texture texture;
 texture.loadFromStream(stream);
```

Bonus Nb.2
===

It also provides two functions, one to load a ```TiXmlDocument``` from a file with ```gd::String``` and one to save it to a file.

### CODE REVIEW

**Comment by 4ian** [comment]
I'm starting to think that gd::String, gd::FileStream and all the related classes should be put in a separate open-source general purpose library to have cross platform Unicode capabilities ^^

**Before merging**, could you squash the commits into a single one? (or more than one, but mainly be sure to remove the "Fix SFMLFileStream", "Forgot some files", "Merge remote-tracking branch 'upstream/master'", "	Improv the gd::FileStream tests")
To have clean history and to not pollute it with these commits :)

**Comment by victorlevasseur** [comment]
Not a bad idea. However, the wxString conversion stuff is only relevant for GDevelop (may have a way to allow users to extend the conversion capabilities of the class).

You can safely "squash and merge" with Github if your want.

**Comment by 4ian** [comment]
The library could have a CMake build option to add support for wxWidgets' wxString, and another one for SFML, and a last one to add functions for TinyXML ;)

I'm thinking about it because you're doing complex work on it and this should get more recognition, and C++ developers should not have to worry about this and be able to use out-of-the-box a library that is easy to use (i.e: working like the standard library) and cross-platform.

I will squash and merge this soon if it's ready!

**Comment by victorlevasseur** [comment]
It's ready :)

**Pull request merged**
