### PR TITLE
[Experimental] Native android export

### PR DESCRIPTION
**Pull request by 4ian**
I've made some refactoring and made an experimental exporter to see if SFML powered games could be run on Android.
I've made a really quick explanation about it here: http://4ian.github.io/GD-Documentation/GDCpp%20Documentation/d5/dfa/class_android_exporter.html

The result is that simple games are working, with great performances but I've got some graphical glitches with some objects and weird crash from time to time on a larger game. 

I'll probably merge this even if the Android exporter is not working as it's not visible for end users for now and there are some improvements nevertheless.

### CODE REVIEW

**Comment by victorlevasseur** [comment]
Which version of SFML should I use ?

**Comment by 4ian** [comment]
Use the latest master from https://github.com/SFML/SFML : clone it and follow **Retrieving and Building SFML** from https://github.com/SFML/SFML/wiki/Tutorial:-Building-SFML-for-Android (build and install `armeabi-v7a` for devices and/or `x86` for simulator like genymotion). Once you've exported a game, do `ndk-build`, `ant debug` and `adb install` as explained in **Building and Executing the Android Example**.

Note that by default, exported game are built for x86. You can change these lines in jni/Application/mk :
```
APP_ABI := armeabi-v7a
# APP_ABI := x86
```

and then re-run `ndk-build` and the other commands to build an APK for an Android phone. :)

**Comment by victorlevasseur** [comment]
If I understood correctly the process, there's no need to update the SFML version used by GDevelop itself ?

**Comment by 4ian** [comment]
Exactly, what the exporter creates is a stand-alone project which can be compiled with a Android SDK/NDK in which there is a version of SFML installed. This version of SFML installed in the Android NDK is totally different.

**Comment by victorlevasseur** [comment]
I get an error when **previewing** a native game inside GDevelop (with this exporter enabled) : 
```
cc1plus.exe : No such file or directory
```
Don't know if it's related to the change of Exporter

**Comment by 4ian** [comment]
Mmm sounds strange to me that the exporter broke the code to launch the compiler.
Did you updated it recently?

**Comment by victorlevasseur** [comment]
No, I'm trying again with TDM-GCC 4.9.2...

**Comment by victorlevasseur** [comment]
That's strange. The official GDevelop is working but not the one I built myself (even with MinGW 4.9.2). I still have this error message.

**Comment by victorlevasseur** [comment]
There's no problem with the master branch. The problem **only occurs on this branch** (no matter if I enable the AndroidExporter or not).

**Comment by victorlevasseur** [comment]
I should have looked at the compilation log (instead of the error panel of GDevelop), the full error message is  : 
```
cc1plus.exe: fatal error: E:\Developpement\GD\Binaries\Output\Release_Windows/CppPlatform/include/GDCpp/GDCpp/Runtime/EventsPrecompiledHeader.h: No such file or directory

compilation terminated.
```

**Comment by victorlevasseur** [comment]
The commit I merged in your branch fix the issue (and also include the Extensions includes).

**Comment by victorlevasseur** [comment]
I had another problem when doing ````ndk-build``` on Windows : 
```
jni/main.cpp:105:57: error: invalid conversion from 'int (*)(RuntimeContext*)' to 'void*' [-fpermissive]
           if (scene->GetName() == "New scene") function = &GDSceneEventsNew_32scene;
                                                         ^
jni/main.cpp:110:68: error: no matching function for call to 'CodeExecutionEngine::LoadFunction(void**)'
             scene->GetCodeExecutionEngine()->LoadFunction(&function);
```

I'll send a commit that fix it soon.

**Comment by 4ian** [comment]
Thanks for the fixes. Oops I though that I had fixed the wrong function type and the extra &... I must have fixed it while testing and not in the code generation.

**Comment by victorlevasseur** [comment]
It's almost working : I get a missing file when doing ```ant debug```. The file missing is ```project.properties```. Where can I get it ?

**Comment by victorlevasseur** [comment]
Ok, need to do ```android update project --target "android-23" --path .``` as written in SFML tutorial.

**Comment by victorlevasseur** [comment]
Done.

Is there a #define to know if GDCpp and the Extensions are built for Android ? So that I can attempt to fix to the tiled sprite object ?

**Comment by 4ian** [comment]
`#if defined(ANDROID)` :wink:

**Comment by 4ian** [comment]
> (The platformer game works perfectly on my Nexus 7 2013 tablet)

I'll check again with the updates made to TiledSpriteObject :)
I had a crash during a scene change, could you try a game with more than one scene?

Also I can't compile anymore with `ndk-build`:
```
Users/florian/Desktop/android-export/jni/Extensions/TextObject/Extension.cpp:26:62: error: expected primary-expression before '>' token
     gd::ObjectMetadata & obj = extension.AddObject<TextObject>(
```

Any idea why? I merged your changes related to templated object creation before doing the PR but I guess I didn't check it was still working for me. That's strange.

**Comment by victorlevasseur** [comment]
Is TextObject.h included ?

Le mer. 10 févr. 2016 à 18:56, Florian Rival <notifications@github.com> a
écrit :

**Comment by victorlevasseur** [comment]
Are you sure the GDCore/GDCpp file are updated in GDevelop folder and in
the exportation folder (it seems that if the file already exists, it's not
replaced) ? Because it's working perfectly on my side.

**Comment by 4ian** [comment]
No worries my directories were all messed up :)

**Comment by victorlevasseur** [comment]
I'll try (I manage to make ndk-gdb works)

Le mer. 10 févr. 2016 à 19:35, Florian Rival <notifications@github.com> a
écrit :

**Comment by 4ian** [comment]
The game is was testing on my phone is not crashing on startup :/ But working great on the simulator. I'll check if it's working again by going back to a previous commit. There is still a crash when changing a scene, looks like it's not related to SFML or OpenGL (but in this case, it should work on desktop too).
I'll send you the game if you're interested to see if we can find why it's crashing.

**Comment by victorlevasseur** [comment]
I've no crashes when changing scenes on my tablet.

**Comment by victorlevasseur** [comment]
Which game were you trying ? (I'm testing with the platformer **project template**)

**Comment by 4ian** [comment]
The crash on startup was related to a compilation mismatch between x86/armv7 ^^' (better use `ndk-build clean` if you're unsure, to clean every object file).
So TiledSprite are rendered properly now and performance looks good! :+1: 

For the crash on scene changing, it's in one of my games, I'll dig a bit to see what's going on and/or if I can reproduce it in an example. I tried ndk-gdb but no stack trace (only function named ????). I took a look at the devices logs and I got a stack trace, but it was changing between runs. Often it crashed while deallocating objects related to the platform behavior.

**Comment by 4ian** [comment]
@victorlevasseur Here is a minimal example: [crash-example.zip](https://github.com/4ian/GD/files/127063/crash-example.zip)

Click on the big button in the middle on Android and it will crash. It's surely related to the platforms but I'm not sure why.

**Comment by victorlevasseur** [comment]
I'll try ASAP

**Comment by 4ian** [comment]
Cool let me know if you can reproduce the crash and if you have any idea on how to debug it efficiently :)

**Comment by victorlevasseur** [comment]
It also crashes on my tablet. Investigating...

**Comment by victorlevasseur** [comment]
It get a stack trace from ndk-gdb : 

```
#0  0xaee21e44 in __tree_is_left_child<std::__1::__tree_node_base<void*>*> (
    __x=0xaec5d174)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/__tree:68
#1  std::__1::__tree_next<std::__1::__tree_node_base<void*>*> (__x=0xaec5d174)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/__tree:159
#2  0xaef60824 in operator++ (this=<optimized out>)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/__tree:747
#3  ScenePlatformObjectsManager::~ScenePlatformObjectsManager (
    this=0xaec5d16c, __in_chrg=<optimized out>)
    at jni/Extensions/PlatformBehavior/ScenePlatformObjectsManager.cpp:8
#4  0xaef5b040 in std::__1::pair<RuntimeScene* const, ScenePlatformObjectsManager>::~pair (this=0xaec5d168, __in_chrg=<optimized out>)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/utility:248
#5  0xaef5a4b0 in ~__value_type (this=0xaec5d168, __in_chrg=<optimized out>)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/map:617
#6  __destroy<std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager> > (__p=0xaec5d168)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/memory:1589
#7  destroy<std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager> > (__p=0xaec5d168, __a=...)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/memory:1487
#8  std::__1::__tree<std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager>, std::__1::__map_value_compare<RuntimeScene*, std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager>, std::__1::less<RuntimeScene*>, true>, std::__1::allocator<std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager> > >::erase (
    this=0xaf09f358 <ScenePlatformObjectsManager::managers>, __p=...)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/__tree:1985
#9  0xaef59f20 in std::__1::__tree<std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager>, std::__1::__map_value_compare<RuntimeScene*, std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager>, std::__1::less<RuntimeScene*>, true>, std::__1::allocator<std::__1::__value_type<RuntimeScene*, ScenePlatformObjectsManager> > >::__erase_unique<RuntimeScene*> (
    this=0xaf09f358 <ScenePlatformObjectsManager::managers>, __k=
    @0xab4e8254: 0xa27ff810)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/__tree:2007
#10 0xaef589e4 in erase (__k=<optimized out>, this=<optimized out>)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/map:1077
#11 PlatformBehaviorCppExtension::SceneUnloaded (this=0xa2693500, scene=...)
    at jni/Extensions/PlatformBehavior/Extension.cpp:462
#12 0xaee70304 in RuntimeScene::~RuntimeScene (this=0xa27ff810,
    __in_chrg=<optimized out>) at jni/GDCpp/GDCpp/Runtime/RuntimeScene.cpp:69
#13 0xaee9b204 in std::__1::__shared_ptr_emplace<RuntimeScene, std::__1::allocator<RuntimeScene> >::__on_zero_shared (this=0xa27ff800)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/memory:3738
#14 0xb3a7e22c in __release_shared (this=0xa27ff800)
    at /tmp/ndk-user/tmp/build-libc++/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/memory.cpp:61
#15 std::__1::__shared_weak_count::__release_shared (this=0xa27ff800)
    at /tmp/ndk-user/tmp/build-libc++/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/memory.cpp:86
#16 0xaee99950 in std::__1::shared_ptr<RuntimeScene>::~shared_ptr (
    this=0xab4e831c, __in_chrg=<optimized out>)
    at E:/Developpement/Outils/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/include/memory:4448
#17 0xaee98c5c in SceneStack::Step (this=0xab4e86b0)
    at jni/GDCpp/GDCpp/Runtime/SceneStack.cpp:36
#18 0xaef4e37c in main (argc=0, argv=0x0) at jni/main.cpp:120
#19 0xaee1f73a in sf::priv::main(sf::priv::ActivityStates*) ()
   from E:\Developpement\GDevelop-android-export\obj\local\armeabi-v7a\libsfml-example.so
#20 0xb3b53e72 in sf::priv::ThreadImpl::entryPoint(void*) ()
   from E:\Developpement\GDevelop-android-export\obj\local\armeabi-v7a\libsfml-system.so
#21 0xb6d41460 in __pthread_start(void*) ()
   from E:\Developpement\GDevelop-android-export\obj\local\armeabi-v7a\libc.so
#22 0xb6d1bb44 in __start_thread ()
   from E:\Developpement\GDevelop-android-export\obj\local\armeabi-v7a\libc.so
#23 0x00000000 in ?? ()
```

**Comment by 4ian** [comment]
Nice stacktrace (much more complete than the ones I had), seems related to ScenePlatformObjectsManager and scene unloading!

**Comment by blurymind** [comment]
This is awesome progress guys. Gaining native android support will attract a lot of new users

**Comment by 4ian** [comment]
I'm also experimenting with another alternative: using Cocos2d game engine, which would bring cross platform/JS compatibility with native rendering on Android/iOS/Mac/Windows/Linux and HTML5 for web games.

**Comment by 4ian** [comment]
See this issue for discussions about this alternative: https://github.com/4ian/GD/issues/238 :smiley:

**Comment by blurymind** [comment]
I've heard a lot of good things about cocos2d in the past. It is a very solid and battle tested as a mobile game development engine- both games and apps. If you manage to integrate it with gd you will also have to maintain only one engine rather than two. The other advantage of course would be the updates that it gets. It seems like a better choice than further implementing sfml, but also a lot more work. I think it would be worth it in the long run as it is more advantageous

**Comment by victorlevasseur** [comment]
Did you manage to catch the Platformer bug ?
I may have an idea (I'll test it as soon as I can get my tablet) : 
```c++
for (std::set<PlatformBehavior*>::iterator it = allPlatforms.begin();
		 it != allPlatforms.end();
		 ++it)
{
	(*it)->Activate(false);
}
```
Here ```Activate(false)``` deactivates the platform behavior but also removes the platform from the ```ScenePlatformObjectsManager``` (by calling ```OnDeActivate() of the behavior``` : 

```c++
void PlatformBehavior::OnDeActivate()
{
    if ( sceneManager )
        sceneManager->RemovePlatform(this);

    registeredInManager = false;
}
```

By removing the platform while iterating on it, it may invalidate the ```it``` iterator and cause a crash in the next instruction using ```it``` : ```++it``` of the for loop.

**Comment by victorlevasseur** [comment]
The platformer behavior should be fixed now. :D

**Comment by 4ian** [comment]
Awesome, thanks for the debugging! Will try it soon :)

**Pull request merged**
