### PR TITLE
Some fixes for GCC6 and Fedora 24

### PR DESCRIPTION
**Pull request by victorlevasseur**
Add the missing GLU include.

Need to be tested on other OSes (Windows and MacOS).

### CODE REVIEW

**Comment by 4ian** [comment]
A build failed on Travis CI because of a timeout while downloading SFML, relaunching it and if it's ok I will merge :)

**Comment by victorlevasseur** [comment]
Don't merge it, I'll push another fix.

**Comment by victorlevasseur** [comment]
That's it.
On Fedora 24, the event code loading failed because it couldn't find the libs (SFML, ...) bundled with GDevelop. Adding the RPATH pointing to the GDevelop's folder when building for preview fixes the problem.

**Comment by 4ian** [comment]
Thanks! 👍

**Pull request merged**
