### PR TITLE
howler-sound-manager: pause/resume sounds when Cordova app is being paused/resumed

### PR DESCRIPTION
**Pull request by dos1**
Without it, sounds in Cordova packaged games keep playing on Android when the app is suspended by the user (by switching the app or pressing home screen).

### CODE REVIEW

**Comment by 4ian** [comment]
Looks really nice 👍 I have a few questions:

* Would it be possible to add a short comment to tell that resume/pause are emitted when running with Cordova? And that we need to pause sounds. 😄 
* I've seen `checkForPause`, my only concern here is that the Javascript engine is creating a function each time we play a sound. That's ok on fast desktop devices, but that could add some work to the garbage collector and make the garbage collection pauses more frequent. (maybe that's premature optimisation but I'm a bit paranoid about garbage collection on mobile :)).

Otherwise looks good :)

**Comment by dos1** [comment]
Sure!
Actually, when looking at the diff after submitting, I kinda frowned at duplicated `checkForPause` functions - I'll see what I can do :)

**Comment by dos1** [comment]
Updated!

**Comment by 4ian** [comment]
Sweet 👍 Looks good, merging this now! 
Good job & thanks for the PR 😄

**Pull request merged**
