### PR TITLE
Support for saving project in multiple files ("Folder project")

### PR DESCRIPTION
**Pull request by 4ian**
This implements support for saving and loading projects as "Folder project", meaning that scenesm external layouts and external events are stored into separate files. This can greatly enhance the collaboration on medium/large projects when more than one person is involved. people can keep working on levels in the external layouts for example, or on different scenes then share their files. :smile:

The implementation is done using a `Splitter` class that "cut" some part of the tree representing the whole serialized projects. The new element are containing a reference to the part that were cut (i.e: the other files). I've also moved the part writing JSON/XML files from gd::Project to a separate class (because it's not the project responsibility to manage files).

@victorlevasseur If you have some time, you can pull the branch and check if you can save a few projects as folder projects, and then load them/modify them again :)

This should be one of the last feature added before releasing version 4 (still need to make sure help is easily accessible for the new AdMob banner and do a find/replace in the wiki to replace automatism by behavior). Let me know if you have something in mind apart from these points that should be addressed/fixed before v4 :smile:

### CODE REVIEW

**Comment by victorlevasseur** [comment]
Nice work ! :+1: 
Do you plan to release a beta version ?
For v4, I thing #166 should be fixed and maybe #176.

**Comment by 4ian** [comment]
Yep next version will be marked as a "beta" and released here and on the forum :)
I'll try to address these issues.

**Comment by victorlevasseur** [comment]
What does the content of "referenceTo" XML fiels represents ? Its always "layout/Layouts"

**Comment by 4ian** [comment]
It's either layouts/layout or externalLayouts/externalLayout or externalEvents/externalEvents: it represents the path to the element that should be retrieved.

**Pull request merged**
