### PR TITLE
Bugfix/particle system

### PR DESCRIPTION
**Pull request by victorlevasseur**
By using ```sf::Texture::getNativeHandle()```.

However, it needs SFML 2.3 at least, so I've updated SFML to 2.4.1. SFML is now embedded into the repository so it's more easier to track its updates (we are sure that everybody has the good SFML version and it's also easier for build workers as they wouldn't have been able to update SFML by themselves).

*In fact, I've been building GDevelop with SFML 2.3.1 for months on my computer, that's why I first fixed the bug by use a SFML >= 2.3 feature).*

### CODE REVIEW

**Comment by 4ian** [comment]
I have to check on OS X to be sure we don't have any regression/weird crash.
In particular, I made a adhoc fix at the time in SFML to avoid a crash in the IDE (without being really sure about what is the real problem, that's why it wasn't commited on SFML).

https://github.com/SFML/SFML/issues/824

**Comment by 4ian** [comment]
@victorlevasseur Got this error :/

```
[ 35%] Building CXX object Core/CMakeFiles/GDCore.dir/GDCore/Tools/HelpFileAccess.cpp.o
/Users/florian/Projects/F/GD/Core/GDCore/Tools/FileStream.cpp:62:13: error: constructor for 'gd::FileStream' must explicitly initialize the base
      class 'std::iostream' (aka 'basic_iostream<char>') which does not have a default constructor
FileStream::FileStream()
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:1728:48: note:
      'std::__1::basic_iostream<char>' declared here
_LIBCPP_EXTERN_TEMPLATE(class _LIBCPP_TYPE_VIS basic_iostream<char>)
                                               ^
/Users/florian/Projects/F/GD/Core/GDCore/Tools/FileStream.cpp:68:7: error: no matching constructor for initialization of 'std::iostream'
      (aka 'basic_iostream<char>')
        std::iostream(),
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:1488:14: note: candidate constructor
      not viable: requires single argument '__sb', but no arguments were provided
    explicit basic_iostream(basic_streambuf<char_type, traits_type>* __sb);
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:1493:5: note: candidate constructor
      not viable: requires single argument '__rhs', but no arguments were provided
    basic_iostream(basic_iostream&& __rhs);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:1728:48: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
_LIBCPP_EXTERN_TEMPLATE(class _LIBCPP_TYPE_VIS basic_iostream<char>)
                                               ^
2 errors generated.
make[2]: *** [Core/CMakeFiles/GDCore.dir/GDCore/Tools/FileStream.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
make[1]: *** [Core/CMakeFiles/GDCore.dir/all] Error 2
make: *** [all] Error 2
```

Maybe not related to this PR, I've not tried the latest master which may also be containing this compilation issue.

**Comment by victorlevasseur** [comment]
Weird that GCC doesn't catch this one. I forgot to put the base class initialization that is required as iostream has no default ctor.

**Comment by 4ian** [comment]
Weird indeed. Are you applying a fix on master? If it's the case, you may want to then `git rebase` this PR on `master`.

**Comment by victorlevasseur** [comment]
Yes, coming soon.

**Comment by 4ian** [comment]
Cool! :) I'm somewhat unable to compile master quickly because my SFML folder was erased and I'm not sure about the version I was using before for OS X.
Anyway let me know when you've come up with the fix.

Also concerning SFML embedding, maybe we could use git submodules? (See https://git-scm.com/docs/git-submodule). Basically SFML could be pointing to the SFML git (with a specific commit so that we're sure everyone has the same version). Also, CMake could fetch it in case the submodule has not been fetched (git clone must be called with argument --recursive if you want to automatically fetch the submodule :( So if CMake can take care of it, it would make the life easier if one forget to properly clone the git of GD).

Anyway, for now let's stick the embedded version as you did. If the PR is working properly everywhere we can always rework it to have this fancy submodule system to fetch SFML without having to include everything in the GD git. :)

**Comment by victorlevasseur** [comment]
Yes, I considered this but the git submodule thing is kind of complicated: the default pull command don't fetch and update to the lastest pointed revision of the submodule...

**Comment by 4ian** [comment]
Mmm yes I see.... What about updating then the CMake command that currently fetch the SFML archive by a call to `git clone https://github.com/SFML/SFML.git` and then `git reset --hard somecommit` (in the SFML directory)?
Do you think that would work? That would only need Git (already required to format the version number) and could be a good compromise: no need to include everything, no need to use complicated submodule stuff?

**Comment by victorlevasseur** [comment]
I think we can use submodules but not yet as a custom patch is applied to SFML to make it work with GCC 5.x and 6.x (there's a bug with a not properly exported in the standard lib). So, the best idea now is just to keep SFML directly in the source code.

**Comment by victorlevasseur** [comment]
Is it working on Mac OS X ?

**Comment by 4ian** [comment]
I'm cloning this branch in a fresh repo and testing it :)
Latest SFML version should work as I'm using a recent one on OS X, but with a tiny fix/workaround (see https://github.com/SFML/SFML/issues/824).

I've restarted the server.

**Comment by 4ian** [comment]
@victorlevasseur It's working OK after applying the fix of my last post. 
I'm still a bit reluctant to include the whole SFML lib in the GD git.. Using git to fetch it and apply fixes would be cleaner I think, and it would self-document the custom fixes that are needed (until they are merged into SFML).

**Comment by victorlevasseur** [comment]
Ok, I'll definitely try to improve this. If Git is not available, the script will ask the user to self download SFML and apply the fix to it.

**Comment by victorlevasseur** [comment]
Can I get the Mac OS X fix as a git patch?

**Comment by victorlevasseur** [comment]
Done. You can add your git patch in ExtLibs/SFML-patches and it will be applied by CMake.

**Comment by 4ian** [comment]
This looks super nice! 💖
Here is the patch for OS X (sorry, GitHub don't want to attach .patch file, I had to zip it): 
[02_workaround_OSX_crash_SFViewController.patch.zip](https://github.com/4ian/GD/files/672018/02_workaround_OSX_crash_SFViewController.patch.zip)

Not sure if I can commit directly to your branch? Anyway feel free to add it.
Once it's done I guess we can do a final quick check and merge this. 😊 I really like the git+patch way to get SFML, it's super clean and lightweight. Good job!

**Comment by victorlevasseur** [comment]
Added. The only downside of the current system is that it requires git, an internet connection (I need to update the OBS script to git clone SFML into the package sent to their server) and each time CMake is executed, it will rebuild parts of SFML and redo the linking on all GDevelop targets.

**Comment by victorlevasseur** [comment]
Done.

**Comment by victorlevasseur** [comment]
Can I merge it?

**Comment by 4ian** [comment]
Let's do this! :)

**Pull request merged**
