### PR TITLE
New Text Object editor

### PR DESCRIPTION
**Pull request by victorlevasseur**
A brand new editor for the Text Object. It focuses on the text and is able to show a preview of the text (but without the custom font as wxWidgets can't load a font from file). It has the look&feel of a small text editor. I obviously used wxCrafter to create it.

newtextobjecteditor

What do you think of this design ?

(Do not merge yet as it seems that Travis-CI doesn't build it because of some GD_IDE_ONLY files)

### CODE REVIEW

**Comment by victorlevasseur** [comment]
It's ok now

**Comment by 4ian** [comment]
Looks nice! Is it possible to apply the skin for the toolbar provided by wxSkinHelper? :)

**Comment by 4ian** [comment]
Also, what's the purpose of the "txt" button?

**Comment by victorlevasseur** [comment]
The txt button is here to show a file selection dialog to change the font.
For the toolbar style, I will commit it soon (thought it was already done).

**Comment by 4ian** [comment]
Cool, could you just post another screenshot with the updated toolbar? :)
I think that the "txt" button icon could changed to something more like the font icon of text processing software, that would be more intuitive... Or even a "open file" icon.

**Comment by victorlevasseur** [comment]
Add the GDevelop style to the toolbar and change the icon to an "open" icon.
Still need to add a help link, will do that tomorrow.
newtextobjecteditor2
By the way, the background color of the text area changes according to the text color.
I also have a problem on Linux : the font size doesn't correspond to the "real" font size (of the object in SFML)

**Comment by 4ian** [comment]
There always have been differences between SFML/HTML5/wxWidgets texts even for the same font size... Not sure we can do anything for it. Apart from displaying "The size of the text can be slightly different in the game"

**Comment by victorlevasseur** [comment]
I added a help link and made the font size more consistent. It should be approximately the same as in SFML (tested on Windows 10 and Fedora)

**Comment by 4ian** [comment]
Strange issue on OS X: when opened, the dialog has a tiny size. Whenever I start to resize it, it goes back to a normal size
screen shot 2015-08-09 at 22 36 58

**Comment by victorlevasseur** [comment]
Isn't it related to Retina ? (try to change the initial size of the window).

Le dim. 9 août 2015 à 16:40, Florian Rival <notifications@github.com> a
écrit :

**Comment by victorlevasseur** [comment]
The problem may be related to the default size of the window set with **SetSizeHints** with wxCrafter. I removed it (set the default size to -1, -1) and just kept the minimum size. Can you tell me if it works better ?
If not, you can still try to use **SetSize()** on TextObjectEditor for Mac OS X only.

**Comment by 4ian** [comment]
The default size is good now :+1:

**Comment by victorlevasseur** [comment]
Everything is ok. I didn't add the "smooth" option as it seems that it doesn't work anymore.

**Comment by 4ian** [comment]
Yeah that was a hack anyway.. Should be removed from the text object in this case :)
Merging it!

**Pull request merged**
