### PR TITLE
Add a random range function

### PR DESCRIPTION
**Pull request by Lizard-13**
This adds a `RandomRange(min, max, step=0)` function, it's self-explanatory but I want to note it works for negative ranges (for example RandomRange(-15, -10, 0.1)), but always with positive steps and min value < max.
Check it carefully, in case you find something suspicious, also I would like to ask if you prefer on the C++ implementation to use std::floor, an explicit (int) casting or an implicit casting as I've done here :)

### CODE REVIEW

**Comment by 4ian** [comment]
I wonder if we should name the function `RandomInRange(x,y,step)`, as the result is not a "range" (which is something that exists in languages like Python) but an integer.
Also maybe it would be a good idea to have `RandomFloatInRange(x, y)`, which would return a floating number between x and y?

That could eliminate the necessity for a "step" argument (I'm afraid people would not really understand why it's there). You either want integers, in which case you have Random(x), RandomInRange(x,y) or you want a float, in which case you have RandomFloatInRange (and RandomFloat??)

**Comment by 4ian** [comment]
> Check it carefully, in case you find something suspicious, also I would like to ask if you prefer on the C++ implementation to use std::floor, an explicit (int) casting or an implicit casting as I've done here :)

I'm afraid that one solution (casting maybe) is gonna make the result biaised... Let me double check

**Comment by Lizard-13** [comment]
As you like, the step is useful to get random numbers in the form (2, 4, 8) or (0.01, 0.02, 0.03) without the need of module, multiplication and division to convert the integers or floats.
Since the Random section is a bit empty (only Random inside), maybe we can do as you are saying, but adding these:
`Random(int)`
`RandomFloat(float)`
`RandomInRange(int, int)`
`RandomFloatInRange(float, float)`
`RandomWithStep(int, int, int)`

**Comment by 4ian** [comment]
@Lizard-13 This looks good! Let's use these names :)

**Comment by Lizard-13** [comment]
Added!, and there is a small random test project too.
The implicit casting now casts a `float` coming from the `std::floor` (almost an `int`), so there should be no problem :)

**Comment by 4ian** [comment]
Looks good! We should maybe added in the description that for floats, min is inclusive and max is exclusive (i.e: RandomFloat(2) will never return 2 but can return 0, same for RandomFloatInRange(a, b)).

Merge this now! Thanks for working on this! 👍

**Comment by Lizard-13** [comment]
Maybe, I would write about it on the new wiki but I have no idea where to put it :upside_down_face:

**Comment by 4ian** [comment]
@Lizard-13 Yes true, I think there is a missing wiki category in the left menu about all the features that aren't covered by Objects/Behaviors/Events (so mainly actions/conditions/expressions not related to objects/behaviors). Still trying to find a name for it.
For now you can always write a page and give me the link there - I'll then attach it to a part of the wiki :)

**Comment by 4ian** [comment]
Great!! Thanks for writing this :) I've moved it here: http://wiki.compilgames.net/doku.php/gdevelop5/all-features/expressions

And I'll try to complete other missing pages about features that weren't documented. Last nice addition would be to add links to help directly in the IDE for all of these features.

**Pull request merged**
