### PR TITLE
No shared_ptr for RuntimeObjects and SceneStack

### PR DESCRIPTION
**Pull request by victorlevasseur**
**Needs heavy testing** as the debugger has been reworked not to use weak_ptr anymore (the debugger is now notified through ObjInstanceHolder when an instance is created or removed).

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for this! :) What kind of testing do you need so that we can validate that everything is all right? Testing with a few games? Maybe adding a few unit tests would help to be confident that everything is working?

**Comment by victorlevasseur** [comment]
Not really easy to test the debugger with a unit test.

**Comment by victorlevasseur** [comment]
I think we can merge this. Did some basic testing with the debugger and no crashes appeared. I'll talk about the nightlies on the forum so that people can try to test them (and may report issues related to this).

**Comment by victorlevasseur** [comment]
Added more commits related to the Clone() function and the use of make_shared/unique instead of the smart ptr constructors. If it's ok, as there's a conflict, I'll squash the commits and manually merge them into master.

**Comment by 4ian** [comment]
Have you tried to do a rebase?

Whenever you make a branch and changes are added to master, `git rebase` is a good thing to do: your branch is updated so that it starts from master. Basically, master is fetched and every commit of the branch is applied one by one. If there is a conflict, you must fix it and do `git rebase --continue`.

If you want to try it, be sure to make a copy of your branch. Once you've done it, go back to this branch, then do `git rebase master`. Git will fetch master and apply all commits one by one. One should make a conflict, do the changes to fix the conflict and do `git rebase --continue`. `git rebase --abort` if something goes wrong (or just go back to the copy of the branch that you've made before).

When you're done with the rebase, you can check (`git log`) that all your commits are here. You can compile and try that everything is all right. Then you can do a push force and this PR will have the updated commits that do not conflict anymore :)

**Comment by 4ian** [comment]
Give it a try and if it's too difficult, just merge master into the branch, fix the conflicts and we'll squash this PR before merging.

**Pull request merged**
