### PR TITLE
Improve code

### PR DESCRIPTION
**Pull request by victorlevasseur**
See the commits' names for detail.

### CODE REVIEW

**Comment by 4ian** [comment]
That's really great that you've added tests for EventsCodeGenerationContext and InitialInstancesContainer!! :D
I'm a bit concerned by the use of exceptions for the camera. I think it would have been good to just check if the camera index is < to the number of camera on the layer.
It's a bit more verbose (not that much in fact) but it will avoid catching all exceptions (`catch(...)`) and I prefer to avoid exceptions handling in code that can be used a lot during the game (for performance reasons in particular).

**Comment by 4ian** [comment]
Looks good! Tell me if you think it's ready to merge :)

**Comment by victorlevasseur** [comment]
It's ready.

**Comment by victorlevasseur** [comment]
By the way, take a look at the no_shared_ptr branch on my fork. Currently trying to replace std::shared_ptr with std::unique_ptr where std::shared_ptr is not really appropriate (so almost everywhere except for resources management).

**Pull request merged**
