### PR TITLE
Update AudioExtension.cpp

### PR DESCRIPTION
**Pull request by ale26reg**
Perhaps, there was missed a few parameters in the actions strings.

### CODE REVIEW

**Comment by 4ian** [comment]
I'm afraid this could make the whole action a bit verbose.. What do you think? Any idea about this @Lizard-13 @blurymind?

**Comment by blurymind** [comment]
@4ian perhaps the extra parameters would be better if optional or split into separate commands to set the extra parameters.

**Comment by blurymind** [comment]
I am actually not entirely sure how this would be represented in the editor. This change seems to add new parameters to a function

**Comment by Lizard-13** [comment]
What do you think about: `Play sound "Sound.wav", volume: 100, repeat: yes` ?, it gives a lot of information with little extra string, I think the pitch is not so important :)

**Comment by blurymind** [comment]
@Lizard-13 thats even more verbose xD

**Comment by blurymind** [comment]
anyways, I think the code is adding a new action - to play a sound. The syntax wont matter to the end user- since they will probably only see this in gui

@ale26reg could you make a screenshot please?
Also what happens if the user doesnt define the extra parameters- does the sound still play?

I personally like the idea of having more control and these features are actually cool, since they can give us more flexible gameplay logic.

**Comment by Lizard-13** [comment]
@blurymind He is not adding extra parameters, he is just changing the event text to show those values, the parameters are defined some lines below ;)
Also, are you sure it's even more verbose?, I'm just shortening the long text :?

**Comment by blurymind** [comment]
@Lizard-13 ah I see.. sorry, my understanding of how the cpp part of gdevelop works is still a bit limited

**Comment by ale26reg** [comment]
@Lizard-13, Yes, we can leave pitch and make string even more shorter: `Play sound "Sound.wav", vol.: 100, loop: yes`. @4ian, @Lizard-13, @blurymind, I don't know, should we show this values in the action strings (I just noticed that not all parameters - accidentally, or specially - are shown in the action strings), but I don't think that it is looks a verbose: [Screenshot](http://prntscr.com/gxg3f4)

**Comment by blurymind** [comment]
@ale26reg I personally think that it looks good 👍

**Comment by ale26reg** [comment]
@blurymind, For the first, I'm not a programmer; absolutly not. I'm here because I'm making Russian translation of GD, so all what I can do is just to manipulate with an already existing strings (conditions, actions e.t.c.). For the second, as this is a built-in function (made by 4ian if i don't mistake), there already exists other actions that allow you to pause or stop playing music/sound file. I just can't imagine situation when you'll really need to stop looping without stopping playing the sound.

**Comment by 4ian** [comment]
@blurymind Sounds started on a channel and looping can be stopped using the dedicated action for doing so. Sounds started without a channel and looping can only be stopped by changing to a scene that stops all sounds when it is started.

**Comment by 4ian** [comment]
@ale26reg I agree that `Play sound "Sound.wav", vol.: 100, loop: yes` is nice too and less verbose :)

**Comment by 4ian** [comment]
Looks good, merging this now! Thanks @ale26reg!

**Pull request merged**
