### PR TITLE
Add support for extensions declared in JavaScript

### PR DESCRIPTION
**Pull request by 4ian**
- [x] Fix all TODOs
- [ ] Add links on the wiki about "Extending GDevelop" to the READMEs written in this PR.
- [x] Document callbacks + add examples with console.log in the dummy extension.
- [x] Document initialization code + example.
- [x] Expose behaviors
- [x] Expose behavior shared data
- [x] Expose objects
- [ ] Expose object editor (for now, use a properties editor like AdMob object)
- [x] Expose objects instances properties

This is a first version of support of extensions declared in JavaScript (as opposed to the use of C++ extension declarations and bundling inside GDevelop.js (libGD.js)). Objects and behaviors are not supported in this first version!
I have a few ideas to make this going to the next level, but should be enough for now.

### CODE REVIEW

**Comment by blurymind** [comment]
@4ian this is a fantastic feature that will enable doing very interesting things with the engine much faster! Thank you for working on it. The readme is very welcoming too. Will have to play with it in the weekend 😸

**Comment by 4ian** [comment]
I hope to have something working with the behaviors and objects for next week :)

**Comment by blurymind** [comment]
@4ian it is impressive how fast you are making progress with this. Thank you again for working on this feature =)

**Comment by 4ian** [comment]
Will probably release this with support for behaviors.

Objects are a bit harder as they also need to register an editor and a renderer for the scene editor. In a first version the objects registered will be given the default `PropertiesEditor`, which will display and allow to edit the properties of the object. Support for customizing the editor will come later. 
It's a bit more work as editors are written with React, using JSX. Usually JSX is transformed by Babel/Webpack but for extensions, JS files are loaded at runtime without any transformation. It will also be difficult to expose the existing components as they are already transpiled. Will probably stay with properties and if we need something more powerful we can add more properties types.

**Comment by blurymind** [comment]
@4ian awesome work!!  :o

Being able to go as far as declaring a custom editor interface some day would be mind blowing, but not that essential. We can already edit the interface of the newIde without need to recompile c++ code

I think that your plan for this is very good 

I guess that for my long therm ambition to be able to edit yarn data inside gdevelop with an embedded yarn - the only thing I would need is to have a button somewhere to launch it for creation/editing of story resource json files - similar to the way piskel is launched for image files. Not sure still if that would be as part of a behavior or an actual game object yet

**Comment by 4ian** [comment]
I've updated the README about declaring extensions: https://github.com/4ian/GD/blob/1f04965fdf2a71a62724cf986221b85369f9d024/newIDE/README-extensions.md

Hopefully the example extension should be enough, will add more documentation later if needed :)

**Comment by blurymind** [comment]
I was thinking the same thing as @Wend1go 

The very first thing one needs to know is the game event loop 👍 
The init process (runs once onload)
The update Process (runs every frame)

Would be nice to have it in the examples :)

**Comment by 4ian** [comment]
> Shouldn't this be:
"Extensions/ExampleJsExtension/examplejsextensiontools.js"?

Yes good catch!

I think that what you need is where to put code for gdjs.RuntimeBehavior, or how to register callbacks when a scene is loaded/unloaded. Let me document these.

**Comment by blurymind** [comment]
Awesome!! This makes it so clear now 🤓

**Comment by 4ian** [comment]
Will probably merge this this week-end or earlier! :)

**Comment by 4ian** [comment]
Merging this now. Earlier is better :)
I'll add support for objects later.
I also have to something to filter the example extension GDevelop is not running in development mode :) But in development it's good to have it so you have a sandbox to play with to experiment or see how it is done!

Please remove **public/libGD.js**, so that a newer version will be loaded, and restart GDevelop (with Electron).
Let me know if something is not clear in the README or if you have any problem.

**Pull request merged**
