### PR TITLE
Experimental Cocos2d-JS export and native android export

### PR DESCRIPTION
**Pull request by 4ian**
This add the (hidden) native android export with SFML (see https://github.com/4ian/GD/pull/246) and support for exporting using Cocos2d-JS (for HTML5 games).

I've been using the Cocos2d export with one of my game and it's working great. I started a page on the wiki to explain how to install Cocos2d and export a game to native platforms: http://wiki.compilgames.net/doku.php/gdevelop/tutorials/howtoexportwithcocos2dx.
Cocos2d could be promoted as the default engine for rendering HTML5 games in preview and exports if it's working great in the future.

### CODE REVIEW

**Comment by blurymind** [comment]
can't you just include cocos to be a part of gdevelop?  :)

**Comment by 4ian** [comment]
Cocos2d-x is ~400mb, compressed :/

**Comment by 4ian** [comment]
Note that the HTML5 version of the engine *is* included. When you export your game, you can distribute it as a HTML5 game just like now. But you have to download the full Cocos2d engine to export the game to native platforms.

**Comment by blurymind** [comment]
perhaps gdevelop could include a script that automatically downloads and installs cocos?

**Comment by blurymind** [comment]
is cocos native android export better than sfml's?

**Comment by 4ian** [comment]
SFML Android export is super-fast as games benefit from the C++ game engine, but games exported with Cocos2d have good performances too. Cocos2d is more mature and has more exports options. 
Also, the performance are better compared to a game exported with the traditional HTML5 export (pixi.js) and then packaged with Intel XDK/Cordova/Crosswalk. In particular, loading times are really fast with Cocos2d.

**Comment by blurymind** [comment]
are you going to support both cocos2d and SFML android native?

**Comment by 4ian** [comment]
Small note to say that these new experimental exporters landed in GD 4.0.91 :) http://forum.compilgames.net/viewtopic.php?f=18&t=7832

**Pull request merged**
