### PR TITLE
Update newIDE to Electron 2.0.7

### PR DESCRIPTION
**Pull request by 4ian**

### CODE REVIEW

**Comment by blurymind** [comment]
Thank you. This should sort out
https://github.com/4ian/GD/issues/572

**Comment by 4ian** [comment]
#572 is already fixed by https://github.com/4ian/GD/commit/9a551673e8c8c0448583d5592d37f829349b6599 ;) 

Though it's nice to stay up to date with Electron to avoid potential similar issues in the future for the IDE and benefit from bug/security fixes :)

**Comment by 4ian** [comment]
This is blocked by https://github.com/4ian/GD/issues/585

**Comment by 4ian** [comment]
Merged this. We still have to remove `transparency: true` and find a better solution for older/incompatible device on which flickering occurs (https://github.com/4ian/GD/issues/585)

**Pull request merged**
