### PR TITLE
TileMapObject memory consumption optimization

### PR DESCRIPTION
**Pull request by victorlevasseur**
In this PR, I changed some parts of the Tileset implementation. It now uses less memory and avoid crashing GDevelop when the amount of tiles is too high.

**The changes in detail :**
* the collidable property of **all** tiles is stored in a ```std::vector<bool>``` (the index is the tile id)
* only non-default hitboxes are stored inside a ```std::map<int, TileHitbox>``` (the tile id is the key)
* the tile texture coordinates (```TileTextureCoords```) are calculated on-demand (so the Tileset::Generate method was removed)
* because of these changes (and to take advantage of them), the ```TileSet``` class serialization format has changed : I introduced a ```version``` attribute to detect the old TileMapObject serialization format. It has the nice side effect to reduce the size of the gdg file.

*Now, the Tilemap object supports very big tilesets : tested with a 3000 * 2000px tileset with 1 * 1px tiles ! (GDevelop was crashing with the old version)*

**EDIT** : I just saw another possible memory problem : to avoid it, ```TileSet::GetTileHitbox``` now only returns by value (it avoids to create the hitbox in the cache if the tile has a default hitbox) and ```TileSet::GetTileHitboxRef``` has been created to get a non-const reference to the hitbox (if the hitbox doesn't exist in the cache, it is created). (see the difference between these two methods which were overloads before : 3321b71)

### CODE REVIEW

**Comment by 4ian** [comment]
I've not a lot of time to review the PR this week, is it good to merge? :)

**Comment by victorlevasseur** [comment]
I think so. But I experienced some random crash (sometimes, when I doesn't launch a game ith gdb...) at scene change (with the last master and this change) so I don't know what is the cause : this PR or the scene stack or something else.

**Comment by 4ian** [comment]
:/ If you fetch the latest master without these changes, are you able to make it crash?

**Comment by victorlevasseur** [comment]
I can't reproduce the issue... :(

**Comment by 4ian** [comment]
Mmm not sure if it's good or not. So you're unable to reproduce the issue both with latest master and master+this PR, right?

**Comment by victorlevasseur** [comment]
We can wait before merging this to be sure. I'm currently developing an RPG template for GDevelop (using this branch because the tileset is huge). I'll tell you if other problems happens. By the way, I also had another bug (only one time too) : one of the sprite image was not loaded when pausing a scene and launching another one. But it never happened again...

**Comment by victorlevasseur** [comment]
Updated for the lastest master branch (v4) and tested with the two Tilemap examples provided with GDevelop. I think it can be merged.

**Pull request merged**
