### PR TITLE
fix outdated path in storybook index.js

### PR DESCRIPTION
**Pull request by blurymind**
it was causing storybook to fail loading

see
https://github.com/4ian/GD/issues/395

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for the fix :) You've included the commits from your previous PR.
You should merge (or rebase, but that's a bit more complicated) `master` branch from this repository into your repository. By doing this, your fork will have the latest commits and you can have a PR that will only contain the latest changes you've made.
Look the GitHub documentation here: https://help.github.com/articles/syncing-a-fork/

I'll merge once you've done it 😄

**Comment by blurymind** [comment]
Ah sorry, I just realized my mistake xD
I will sort this out tonight and do another pull request

**Comment by blurymind** [comment]
Hi, I was wondering, is it possible to do that with github's web interface?

**Comment by blurymind** [comment]
Just made a new pull request here
https://github.com/4ian/GD/pull/403

closing this one

**Pull request closed without merging**
