### PR TITLE
b2TOISolver initialization fix

### PR DESCRIPTION
**Pull request by pstieber**
A non-pointer data member (int32 m_count), was incorrectly being initialized to NULL instead of 0 and gcc 4.9.2 was pointing this out:

```
[ 83%] Building CXX object Extensions/PhysicsBehavior/CMakeFiles/PhysicsBehavior.dir/Box2D/Box2D/Box2D/Dynamics/Contacts/b2TOISolver.cpp.o
/home/pstieber/OutsideSource/gdevelop/GD/Extensions/PhysicsBehavior/Box2D/Box2D/Box2D/Dynamics/Contacts/b2TOISolver.cpp: In constructor ‘b2TOISolver::b2TOISolver(b2StackAllocator*)’:
/home/pstieber/OutsideSource/gdevelop/GD/Extensions/PhysicsBehavior/Box2D/Box2D/Box2D/Dynamics/Contacts/b2TOISolver.cpp:41:10: warning: converting to non-pointer type ‘int32 {aka int}’ from NULL [-Wconversion-null]
  m_count = NULL;
          ^
```
This commit removed the warning.

### CODE REVIEW

**Comment by victorlevasseur** [comment]
The problem is that it's a external library. So, it's not a good idea to
change its source code.

Le ven. 8 janv. 2016 à 20:42, Pete Stieber <notifications@github.com> a
écrit :

**Comment by pstieber** [comment]
I didn't realize it was an external project.  I'll try to push this up to the box2d folks if I can find them.  I'm trying to contribute to your project to build up trust before I open an issue w.r.t. a problem I'm encountering on Fedora 21.

**Comment by pstieber** [comment]
Looks like this code is no longer in the Box2D master branch.  I don't see any other branches. Is it time to update?

**Comment by victorlevasseur** [comment]
You can teel us your bug on the issue tracker.

Le ven. 8 janv. 2016 à 22:41, Pete Stieber <notifications@github.com> a
écrit :

**Comment by pstieber** [comment]
Yes. Will do.  Just wanted to help a little first by contributing some code first.
I was wondering, since Box2D no longer contains the source modified in this pull request:
https://github.com/erincatto/Box2D/tree/master/Box2D/Box2D/Dynamics/Contacts
maybe it would be OK to either:
1. go ahead and merge
2. try using the latest Box2D code via another branch of GD
What do you think?

**Comment by 4ian** [comment]
Box2D version used in GD is version 2.1, latest Box2D version available now is 2.3.1
We could upgrade and check that the behavior of physics powered games are not changed. If the behavior change, then I guess it's safer to keep the current version and apply this fix to suppress the warning (and update to latest Box2d in a next major release of GD breaking backward compatibility).

**Comment by 4ian** [comment]
I merge this, even if we update Box2D later it's better now with this fix. Thanks :)

**Comment by pstieber** [comment]
No problem.  I was trying to provide some cleanup on your project so I could build up some good will so I could submit an issue about a problem I was having with the display of the wxAuiNotebook object, but I was building against the current master branch of the wxWidgets git instead of the WX_3_0_2 tag.  When I switched to version 3.0.2 of wxWidgets, all was well, indicating the problem was in the master branch of wxWidgets, not gdevelop.  I guess I will not be submitting any issues against gdevelop :wink:

Thanks for considering, reviewing and applying my requests.

**Comment by 4ian** [comment]
Thanks for taking the time to check this issue - and for all the PR, really appreciate it. :) Are you submitting an issue on the wxWidgets tracker? Let me know if you need something :)

**Pull request merged**
