### PR TITLE
Camera bug

### PR DESCRIPTION
**Pull request by Wend1go**
Tested @blurymind ' s solution for 2 days and the camera panning bug didn't show up anymore.

### CODE REVIEW

**Comment by Wend1go** [comment]
I wonder what I'm doing wrong since it always puts commits into the pull request that are from whole different branches. :(

**Comment by blurymind** [comment]
@Wend1go glad it worked and thank you for testing :) 
It looks like this pull is getting the commits from your other pull

It has never happened to me before, so not sure what to suggest on this one

**Comment by Wend1go** [comment]
Maybe because I created the pull request for 4ian:master instead of 4ian:camera_bug.
This git(hub) thing is still new to me.

**Comment by 4ian** [comment]
git is based on commits and branches. Here you've made your changes in a branch that also contains the other commits. To have a Pull Request with only "fix get stuck in camera panning mode bug", you must start from master (`git checkout master`), create a branch locally (`git checkout -b mybugfix`) and commit here. As you've already done this commit, you can "import" it into the branch by using its hash (the identifier number): `git cherry-pick 7c111c69330b6cdba0d5f3c9061cfb1f42f2bbaa` (you can find it in the url for example: https://github.com/4ian/GD/pull/546/commits/7c111c69330b6cdba0d5f3c9061cfb1f42f2bbaa)

Then you can `git push` this branch and open a Pull Request where you choose 4ian:master and your branch :)

When you're on a branch, do `git log` to see what commits are on the branch. If there are commits that you don't want, you better start again from master (there a way to remove them but it's quite complicated and risky - you could easily lose your work).

**Comment by 4ian** [comment]
Tell me if you want to try by yourself, otherwise I'll cherry pick by myself your commit on a new PR :)

**Comment by Wend1go** [comment]
I'll try to do it tonight. Otherwise feel free to cherry pick yourself if I haven't done so until the weekend.
So if I understand you correctly I should create a new (empty) branch and cherry pick that one commit from this pull request into it and create a new PR?

I still don't know where exactly I made the mistake though.

The road to this pull request was as follows:
1) Create a pull request from 4ian/master to Wend1go/master (to get my fork up to date)
2) git pull origin master (to get the changes to my local PC)
3) `git branch usability_improvements` and `git checkout usability_improvements`
4) Edit code on branch usability_imporvements and commit to that branch usability_improvements
5) git push origin usability_improvements
6) on github create pull request 4ian/GD master <- Wend1go/GD usability_improvements
7) `git branch camera_bug` and `git checkout camera_bug`
8) Edit code on branch camera_bug and commit to that branch camera_bug
9) git push origin camera_bug
10) on github create pull request 4ian/GD master <- Wend1go/GD camera_bug

As far as I understand `git branch -b branchname` is the short form of `git branch branchname` and `git checkout branchname`.
I'm pretty sure that I was on the correct branch when I commited the changes.

**Comment by 4ian** [comment]
> 6. on github create pull request 4ian/GD master <- Wend1go/GD usability_improvements
> 7. git branch camera_bug and git checkout camera_bug

This is where the problem is I think, you created `camera_bug` **from** `usability_improvements`.
So `camera_bug` includes all commits from `usability_improvements`.
Instead you must first go back to master (git checkout), optionnally but recommended get your fork up to date (PR from 4ian/master to Wend1go/master then git pull).

Only when you are on master you can create a new branch (`git branch camera_bug` and `git checkout camera_bug`).
Otherwise, you creating a branch from a branch (much like on a tree), instead of a branch from master (much like the trunk of a tree) :)

**Comment by Wend1go** [comment]
merged in #549

**Pull request closed without merging**
