### PR TITLE
Fix box2d.js crash when changing scenes

### PR DESCRIPTION
**Pull request by victorlevasseur**
This fix the crash happening when switching scene ~5 times in HTML5 games using box2d.js.

However, the games will still crash after ~20-25 scene changes because of another memory limit. It may be possible to fix this by building box2d.js with empscriptem and the ```ALLOW_MEMORY_GROWTH``` (but I didn't manage to build box2d.js myself :( )

### CODE REVIEW

**Comment by 4ian** [comment]
> However, the games will still crash after ~20-25 scene changes because of another memory limit.

Looks like a memory leak. Box2d is quite stable and it sounds unlikely to me to find a memory leak inside. The implementation of the behavior is most probably leaking memory (emscripten objects that are allocated should have `destroy` called on them after).

**Comment by victorlevasseur** [comment]
So, I think it can be caused by the world not being explicitly destroyed when the scene is unloaded.

**Comment by 4ian** [comment]
It's quite possible indeed!

**Comment by victorlevasseur** [comment]
It's the case. But how can I destroy the world when the physic shared data is destroyed / when the scene ends ? (I hate those garbage collected languages !!!)

**Comment by victorlevasseur** [comment]
I managed to fix the Box2D problem. However, the implementation of shared datas is quite strange : the PhysicsSharedData are instanciated as a property of the runtimeScene Nice, but it's impossible de have two physics behaviors (with distinct names) working in the same scene

**Comment by victorlevasseur** [comment]
I fixed the conflict (in fact, you already add the call to unloadScene in scenestack.js)

**Comment by 4ian** [comment]
> But how can I destroy the world when the physic shared data is destroyed / when the scene ends ? (I hate those garbage collected languages !!!)

The thing is that garbage collected languages offer convenience regarding memory allocation (just create objects and when they are out of scope, they will be destroyed) but on the other hand make it easier for the developer to forget about cleaning up the memory (that was the case here).
Whatever the language is, garbage collected or not, we must think about what the lifecycle of the object will be.

> However, the implementation of shared datas is quite strange : the PhysicsSharedData are instanciated as a property of the runtimeScene Nice, but it's impossible de have two physics behaviors (with distinct names) working in the same scene

Very true, the implementation was made so that two behaviors of the same type, even with distinct name, are not supported.

> I fixed the conflict (in fact, you already add the call to unloadScene in scenestack.js)

Glad that you found the solution! `gdjsCallbackRuntimeSceneUnloaded` is indeed meant to allow behaviors to clean up things before a scene get destroyed (it's analogous to a destructor in C++). Still, I wonder if it's totally safe to call `Box2D.destroy(runtimeScene.physicsSharedData.world)` => Is it possible to have a scene unloaded with a world never properly constructed (i.e: no object instancied with a `PhysicsBehavior`)?

**Comment by victorlevasseur** [comment]
Is it better ?

**Comment by 4ian** [comment]
Looks good now!

**Comment by 4ian** [comment]
On the "Angry Peas" template, the peas are sometime not thrown properly, just like if the impulse added to them was not properly applied... Not sure if it's due to the Box2d update (the physics example works well) but I think it is somewhat related..

**Comment by victorlevasseur** [comment]
I'm not able to reproduce the issue. But the previous fix can't work without the Box2D update (to replace the "VTable" functions).

**Comment by 4ian** [comment]
Yep, well I guess it's not bad to have a newer version of Box2d in any case, but I'm pretty sure this intermittent problem wasn't here before. If you try long enough, there should be a few case where the pea is not launched properly but just falling.
Again it's maybe not a box2d issue, but a problem related to the game/behavior.

**Pull request merged**
