### PR TITLE
Fix Vsync and Max FPS not reactived after a sf::RenderWindow change

### PR DESCRIPTION
**Pull request by victorlevasseur**

### CODE REVIEW

**Comment by 4ian** [comment]
i wonder if the calls to setFramerateLimit and setVerticalSyncEnabled should be added into ChangeRenderWindow instead?

**Comment by victorlevasseur** [comment]
Will do that. By the way, Vsync property is not saved.

**Comment by victorlevasseur** [comment]
Fixed this little problem (SerializerValue::GetInt() used instead of SerializerValue::GetBool()) in 0092841

**Comment by 4ian** [comment]
Nice factoring! Looks good :+1:

**Pull request merged**
