### PR TITLE
gd::String interface improvement and FromCodePoint string expression for games

### PR DESCRIPTION
**Pull request by victorlevasseur**
This PR brings : 
* a new string expression to get a character from its codepoint (in native and JS games)
* a gd::String interface improved (replaced some char32_t by gd::String::value_type and replaced the typedef by the "using" type alias (C++11) )
* Travis CI uses GCC/G++ 5 to really support C++11. Don't know if the the version of clang is fully C++11 compliant... EDIT : Now uses GCC/G++ 4.8 since ba6a7b5

EDIT : The commit e70ff4e adds gd::String::UpperCase() and gd::String::LowerCase(). It also adds their equivalent as string expressions to use in native games and HTML5 ones.

### CODE REVIEW

**Comment by 4ian** [comment]
```Travis CI uses GCC/G++ 5 to really support C++11. Don't know if the the version of clang is fully C++11 compliant...```

Is it mandatory to use GCC5 ? Do you know if we can keep using GCC 4.8.x/4.9.x?

Apart from this, the `To[Lower|Upper]Case` expressions is a really good addition :+1:

**Comment by victorlevasseur** [comment]
You don't like GCC 5 ? It's not mandatory but GCC 4.8/9 still have an experimental support of C++11. (Already using GCC 5 on Fedora)

**Comment by 4ian** [comment]
Just want to be sure that GD can still be compiled on "legacy" OS that have GCC `4.8^` (and I think that it's much more widespread than GCC 5.x for now right?).
Support is maybe experimental but still it's working ok, not sure if GCC 5.x is so much more advanced on this point :)

**Comment by victorlevasseur** [comment]
I'll try with GCC 4.8 tomorrow (4.6 is missing the "using" type alias).

**Comment by 4ian** [comment]
Cool! Let me know how it works :)

**Comment by victorlevasseur** [comment]
I revert Travis CI to GCC 4.8 and it works.

**Comment by victorlevasseur** [comment]
Currently resolving the conflicts introduced by #180...

**Comment by 4ian** [comment]
Ok cool! After merging it I'll update the `.travis.yml` to use the [new Travis build architecture](http://docs.travis-ci.com/user/migrating-from-legacy/) .

**Comment by victorlevasseur** [comment]
You won't be able to use sudo anymore with this new infrastructure.

**Comment by 4ian** [comment]
Yup, but sudo is only used to install packages, and we can do it instead using `addons.apt.packages` (including gcc-4.8) :) I've checked the packages [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) and everything we are using is inside this whitelist.
So that should work and the build should be slightly faster.

**Comment by victorlevasseur** [comment]
Should be ok to merge now.

**Comment by 4ian** [comment]
@victorlevasseur Updated to travis CI container infrastructure: https://github.com/4ian/GD/commit/cde0a7b4a9a74ca23582deaf8adb6ed914ba2312

Works good just as before! :) Builds are longer in fact even if container has 2 core instead of 1.5 -_- but I guess it's because the container is stricter about CPU usage so the build can't "steal" CPU resources. Anyway, at least we are now up-to-date with Travis infrastructure.

**Comment by victorlevasseur** [comment]
Nice :) There's still a problem with AppVeyor. :(

**Comment by 4ian** [comment]
Yes, but the build is so long to start and complete that it's painful to debug :/
Something related to files that can't be copied..

**Comment by 4ian** [comment]
@victorlevasseur Fixed the AppVeyor build! Configuration file added here: https://github.com/4ian/GD/commit/071ef65a951f7e3dce934ccc010e140e8860ace7

It was failing because of a trailing slash in `copyWindowsLibraries.bat ..\..\Binaries\Output\Release_Windows\ ..\..\Binaries\build\ExtLibs\`: the correct call is `copyWindowsLibraries.bat ..\..\Binaries\Output\Release_Windows ..\..\Binaries\build\ExtLibs\`.

Not all tests are launched but at least now it should build and launch tests properly! :smiley:

**Pull request merged**
