### PR TITLE
Import TMX files (Tiled Editor) into TileMap Objects

### PR DESCRIPTION
**Pull request by victorlevasseur**
**(not ready to merge, need testing)**

Add the possibility to import .tmx file into a Tilemap object. These files are the files saved by the Tiled tilemap editor, a very popular tilemap free editor. The goal is to be able to import the tileset (image and configuration), the tilemap and the hitboxes. Only orthogonal tilemaps are supported (obviously).

**Library used :**
It uses tmxparser (https://github.com/andrewrk/tmxparser), an opensource parser using TinyXML2 (both embedded in the extension).

**What is done :**
 - [X] Import the tileset configuration (except the image) : supports spacing and tilesize, not margins currently (as the extension doesn't support it)
 - [x] Import the tileset image : done in 33ff926, imports the image as imported<NUMBER>_<FILENAME>.<EXTENSION> and set this resources as the tileset image.
 - [X] Import the tilemap : the 3 first tile layers are imported into the 3 layers of the object
 - [X] Import the hitboxes : supports only one hitbox per tile, only a rectangle or a polygon

These features need testing.

Note : the hitboxes are imported from tile's objects (tiles' objects can be edited in View > Tile collision editor)

### CODE REVIEW

**Comment by 4ian** [comment]
This would be a great enhancement to be able to import complex tilemaps created with a dedicated software made for this! I'll try to test this feature soon :)

**Comment by alabd14313** [comment]
Can this patch import tilemap terrains and collision bounds?

**Comment by victorlevasseur** [comment]
As written above, it can import collision hitboxes when they are a single convex polygon or rectangle per tile. What do you mean by terrains ?

**Comment by 4ian** [comment]
Do you think it's "production ready" now? :)

**Comment by victorlevasseur** [comment]
It still needs to be tested on Windows.

**Comment by victorlevasseur** [comment]
It's ready to be merged

**Comment by 4ian** [comment]
Mmm there are some conflicts with the current master branch. Could you check if you can merge/rebase by yourself?

**Pull request closed without merging**
