### PR TITLE
Various optimizations (events generated code and game engine)

### PR DESCRIPTION
**Pull request by 4ian**
Still working on it. 
Optimization is applied on GDJS generated code for now but not GDCpp.

### CODE REVIEW

**Comment by victorlevasseur** [comment]
Is the performance gain noticeable ?

**Comment by 4ian** [comment]
Not a lot, maybe a few FPS. On a scene of a large game with  it can still avoid 191 copies (calls to `createFrom`) out of 1059.

**Comment by 4ian** [comment]
I've made another improvement (see https://github.com/4ian/GD/pull/331/commits/4104d7bdc555a60192aa87eff5a580ab9b503626, the changes are quite simple) that greatly reduce the intermittent lags/freeze that could happen in particular when GDJS games are exported on Android. All events list are now generated in separate functions (for GDJS games only, the problem is not affecting GDC++ games), this help reduce the pressure on the garbage collector and the whole JS engine.

On my Android mid-end phone on a large game, I previously had freezes lasting up to 0.5 or 1 second in the worst case. Now it seems that the worst case is a 100/200ms lag. This do not impact raw performance (in terms of FPS) but helps to make the games far more enjoyable. 😊

**Comment by 4ian** [comment]
I've ported the optimisation to reuse objects lists to GDCpp and made another one for StandardEvent:
objects lists were declared for both actions and conditions before launching the conditions, but sometime the conditions are not fulfilled so it's not necessary to prepare the objects lists for the actions. 
For example, if the condition is "Scene begins", it's always false but we created the object lists for all objects used in the actions.

Declarations of objects lists are now deffered to when actions are launched. This is done by declaring a new context and add the code to generate objects declaration when actions are launched. This is lightweight because the new context is marked to reuse the objects lists of the conditions if possible, so no extra copies.

Performance improvement should be quite small on GDCpp, but it's cleaner to have the same logic on both GDCpp and GDJS. And it's important to minimize useless work for GDJS at runtime.

**Comment by 4ian** [comment]
@victorlevasseur Could you make a few tests against existing games? I've checked and did not see any issue with code generation and games but better double check that there is no regressions :)

**Comment by 4ian** [comment]
Merging this as it improves code generation for both GDCpp and GDJS and provides a few more optimizations.

**Pull request merged**
