### PR TITLE
Add Monaco Editor for editing JavaScript events, with autocompletions

### PR DESCRIPTION
**Pull request by 4ian**
Still a work in progress - see TODOs
Original Trello card: https://trello.com/c/W0mYtxMy/80-include-a-real-code-editor-for-javascript-into-gdevelop-5

Next steps: 
- [x] Create examples
- [x] Improve documentation to explain how to use objects (iterate over them)
- [ ] Adapt the theme of the editor (light/dark) according to GD selected theme.

screenshot 2018-08-17 17 56 53
screenshot 2018-08-17 17 57 20
screenshot 2018-08-17 17 58 25

### CODE REVIEW

**Comment by 4ian** [comment]
@Bouh @Wend1go @ddabrahim @blurymind and all who can be interested, I will need help to make sure that the documentation of methods in GDJS/Runtime is properly done :)
What is important to have a good autocompletion is that all methods have parameters and return annotations (`@param {type} name Some description` or `@return {type} Some description`). In particular, it's useful to add the type when it's an object (for example `@param {gdjs.RuntimeObject} object The object to be used` for some function that would take a gdjs.RuntimeObject as parameter).

I've started doing some fixes: https://github.com/4ian/GD/pull/586/commits/f182ed07044f60f25b3643474b951202a84ab8fe
but you find other place in the codebase where the typing is not properly done, feel free to send PRs :)

**Comment by 4ian** [comment]
Merging this now. In case someone want to try early, remember to run `npm install` (or run `yarn`) as a new package is installed (`monaco-editor`). I've used code splitting to make sure that the code editor is not loaded unless some JavaScript code events are actually used.

Monaco Editor is a very powerful editor as it's extracted from Visual Studio Code - so it's battle tested and efficient, with advanced features (like multi selections with Cmd+D or Ctrl+D ❤️). 

Auto completion support should be very good (I've typed almost all the code of the new example with autocompletion 😉). Will be even better as the documentation of GDJS is enhanced to fix any missing type annotation.

I've added examples of this page: http://wiki.compilgames.net/doku.php/gdevelop5/events/js-code which should be enough to get started.

**Comment by Wend1go** [comment]
@4ian I'd like to help with the properties but I have some questions:
- Can I use the "@private" parameter to judge if a parameter is public and needs proper annotations or not? How do I know that a function's parameters need to be updated for the code completion? 
- Should I only correct the parameters in the JS extensions or alco Cpp?
- What is the best way to find out the type of a parameter (string, int, etc)? Is there an easier way than comparing the functions with the Cpp header file?
- Can I add the commits to this branch?

**Comment by 4ian** [comment]
> Can I add the commits to this branch?

In theory you can clone this branch and add commit on it and then open a PR. To avoid doing anything to complex, I'm going to merge this so you can start from `master` branch as usual :)

> Can I use the "@Private" parameter to judge if a parameter is public and needs proper annotations or not?

`@private` is used for a whole method:
* usually if a method is prefixed by `_`(for example, `_constructListOfAllInstances`), it's private.
* more generally, methods that are used only by a given class and should not be called from somewhere else should be `@private`.
* if you're not sure, don't add anything and ask me :)

> How do I know that a function's parameters need to be updated for the code completion?

* First, check if the parameters are properly documented with `@param {type} name description`. If not, it's a good idea to add documentation.
* Otherwise, double check the parameters to make sure that they have a type that is correct (i.e: number, string, boolean or gdjs.XXX). For this, read the function body and see what the parameter is used for. The name is a good hint.
* Double check also that the description is understandable.

> Should I only correct the parameters in the JS extensions or also Cpp?

Only JS: .js files in GDJS/Runtime and .js files in Extensions/XXX

The most important files to document are gdjs.XXX classes (both in GDJS/Runtime and the classes in extensions), in particular the **XXXRuntimeObject** and **XXXRuntimeBehavior**. The rest is usually private stuff for the extension or only used by event.

> What is the best way to find out the type of a parameter (string, int, etc)? Is there an easier way than comparing the functions with the Cpp header file?

I would say not to bother with C++ header files. They can be useful for a comparison by it's not a 1:1 mapping. I would say to just look at:
* first, the name of the parameter
* then, look in the method how the parameter is used to confirm if it's a string, number, boolean or gdjs.XXX

For example, if a parameter is called `object`, good chance that it's a `gdjs.RuntimeObject` (or a subclass). Double check in the method to see how it's used. For example, if `getX` is used on it, it's definitely a `gdjs.RuntimeObject` :)

There is some place in the game engine where objects can be generic JS objects, for example when loading data from the project json. In this case don't bother with it, just stick with {Object} as a type.
If you're not sure you can ask or just ignore the method :)

**Comment by 4ian** [comment]
Merging this now. It will also merge https://github.com/4ian/GD/pull/582 with the newest Electron version.
Remember to do a `npm install` or `yarn` before re-start GD (`npm start` or `yarn start`). Delete `newIDE/app/public/libGD.js` to be sure that you have the latest version :)

**Comment by blurymind** [comment]
This is absolutely fantastic! I am highly interested in how it could be used to develop extensions.
Can it open/save local files in the project folder?

**Comment by blurymind** [comment]
@4ian Accessing external javascript libraries fetched from npm comes to mind :P
Being able to easily include a js file from the project root and use its functions. That kind of thing would be amazing.
Its the kind of thing that a lot of other html5 engines take advantage.

On the question of writing extensions directly in gdevelop- how would that work? From what I understand extensions are located in gdevelop's installation folder, not the project folder.
So will this engine be able to create/edit/save files, create folders and so on in gdevelop's installation folder- where it is looking for them?

**Comment by blurymind** [comment]
I need to give this a good try of course, but my hope is that it will be able to give us lower level access- stuff that can't be done with the event sheet yet

**Comment by Wend1go** [comment]
@4ian thanks for clarification, that should be enough to get started. But It'll take some time since I also have my gyroscope extension in the works.

**Comment by 4ian** [comment]
> Accessing external javascript libraries fetched from npm comes to mind

Do you have any idea of what library you would use?
Also, do you have a link to these npm libraries used in other game engines? I'm wondering what they support exactly (in particular, given how a library is made it may or not may be a good idea to use it especially on mobile (performance or compatibility)).

Let me know if you can give all of this a try.

> But It'll take some time since I also have my gyroscope extension in the works.

Cool let me know if you need help/clarification :)

**Comment by blurymind** [comment]
@4ian there are a few :)
On the top of my head,ones I would love to try using in a gdevelop project:
https://www.npmjs.com/package/bbcode-parser
https://www.npmjs.com/package/one-dollar
https://www.npmjs.com/package/bondage

But there are also ones specifically for gamedev:
https://www.npmjs.com/search?q=keywords:game
:) 

Ultimately would be cool to use some of them in a plugin form. 
 In any case, i think js developers would feel more comfortable being able to actually split their code into files

**Comment by blurymind** [comment]
I gave this a try.It is very impressive :o only thing missing is the syntax coloring.I wonder why its disabled

**Comment by 4ian** [comment]
@blurymind Fixed this bug, thanks :)

Ok, I see what kind of library you want want to use.
As games with GDevelop are not bundled with webpack or anything and running in the browser most of the time, you still have to avoid using libraries using Node.js or native APIs (except if you're 100% sure that you will always use Electron for your game - but even there I would recommend to stay with libraries no requiring Node for better portability of your game).

> On the question of writing extensions directly in gdevelop with this editor- how would that work? From what I understand extensions are located in gdevelop's installation folder, not the project folder.
So will this editor be able to create/edit/save files, create folders and so on in gdevelop's installation folder- where it is looking for them?

For this use case, I would have to do a few changes to have extensions loaded (see `LocalJsExtensionsLoader.js`) from both `GDJS/Runtime/Extensions`, but also from an arbitrary `Extensions` folder located somewhere (or even located in a project directory). This would also need a few changes in the GDJS Exporter (`GDJS/IDE/Exporter.cpp`) so that it supports exporting extensions files that are located in this extra "Extensions" folder. (i.e: look first in project_folder/Extensions, then in User/Documents/GDevelop common extensions/Extensions, then finally in GDJS/Extensions).

For now, extensions are copied in GDJS runtime (inside `newIDE/app/resources/GDJS/Runtime`) by [`node import-GDJS-Runtime.js`](https://github.com/4ian/GD/blob/master/newIDE/app/scripts/import-GDJS-Runtime.js) script (which is itself calling [this script on Windows](https://github.com/4ian/GD/blob/master/GDJS/scripts/CopyRuntimeToGD.bat) or [this one on macOS/Linux](https://github.com/4ian/GD/blob/master/GDJS/scripts/CopyRuntimeToGD.sh)), they are read from there and package into the GDevelop app when built for release.

**Comment by blurymind** [comment]
@4ian I can still include js files without relying on node/electron and use their functions :)
npm is just a package management system/website. Each library has a github and alternative methods to be included in a js project

**Comment by 4ian** [comment]
>  I can still include js files without relying on node/electron and use their functions :)

Yes, exactly. You can also even copy paste the built file/minified version into an external events sheet for now :) Or better, in a separate scene events (otherwise, there is a risk that your external events, and so your code, is duplicated into multiple file).
You can name this scene with the name of the library (it's a bit hacky but better than nothing). Keep reading for a solution that could be done.

> If the built in monaco editor is constrained to the event sheet, most people who want to write a js extension will not use it for that- but will instead use vs code or sublime or some other external editor

Yes, for extensions I still recommend an external editor (the scope of the changes of this PR was to first improve the way we can create JavaScript in GDevelop).

> The only thing I really need is a way to access js/any resource files that are inside the project folder of the game- so I can use them in my script

* So there was an option in GDevelop 4 to add external "source files". It was not integrated yet into GD5 because it was a bit experimental and need careful thinking to avoid creating something that could become a mess.
These "source files" could be a solution to what you want to do (i.e: to include external libraries). You would still need to include them manually in your project folder and add them one by one in the list of source files (but I think anyway you don't want to rely on tons of external files). Here is a [Trello card about this feature](https://trello.com/c/rnmnF4nt/127-add-support-for-adding-arbitrary-external-source-files-javascript-that-are-bundled-with-the-game).

There are a few things to consider: how to specify order of inclusions of files, should the names of the files be preserved or not (in GD4, they were renamed to ext-XXX.js)

* For more complex work, writing an extension is still the way to go I think. One way to make this more convenient/faster/more flexible would be to allow each project to have its directory of extensions. I've [created a card on Trello for this](https://trello.com/c/psHA4Odb/126-add-support-for-extensions-declared-in-the-project-folder-or-in-a-common-folder-external-to-gd-installation-directory).

**Comment by blurymind** [comment]
@4ian is there a simple way to just get files inside the project folder of the game via javascript?
So when writing in the embeded monaco editor, can't we just have some sort of utility function to load js files from the project folder?

something like
```
function IncludeJsScript(url) {
    var script = document.createElement("script"); //Make a script DOM node
    script.src = <project folder>/url; //Set it's src to the provided URL
    document.head.appendChild(script); //Add it to the end of the head section of the page (could change 'head' to 'body' to add it to the end of the body section instead)
}

```

and then in monaco:
 `IncludeJsScript("myEpicFile.js")`

**Comment by 4ian** [comment]
You can simply refer to src with `yourfilename` as it will be relative to the index.html file which is at the root of the exported game folder. It's then the server job hosting the game (or the preview) to serve the given file:

```
function IncludeJsScript(relativePath) {
    var script = document.createElement("script");
    script.src = relativePath;
    document.head.appendChild(script);
}
```

Note that this is "hacky", meaning that there is no official support for doing this for now (unless writing an extension) so be prepared to update this if we find a better solution later 😉 
Also as you're the first to do this, better try by yourself and let me know if you come with something that work and we'll see if we can keep/improve this.

> or maybe something like import x from y ?

This would need a transpiler set up like Babel, which is not doable for now as GDevelop is not using any bundler (for simplicity, speed and control of the output). Node.js is also not yet supporting this (except maybe the very last versions). But it's not a problem of syntax, it's just that GDevelop is based on Vanilla JS, and JS don't have any bundling or module by default.

**Comment by Wend1go** [comment]
I successfully used external JavaScript source files in Sakawochi with GD4 before I switched over to GD5. They are still working in GD5 an I'm still using them. I found the external source files pretty convenient. Would be nice to see the functionality in GD5 again.

**Comment by 4ian** [comment]
Nice! What are you using them for exactly? :) Are you still editing/updating them by directly editing the JSON of the project file?

**Comment by blurymind** [comment]
I am thinking of using the json just as a game resource to be loaded into
memory. Not edited during gameplay. Of course json files could be used as
save states as well. :) Ideally the editor could treat them as a kind of a
resource, but that is already a card on trello i think. Right now i am
thinking in the short term how to get quick results and test things with
this awesome cool built in monaco editor we now have

**Comment by Wend1go** [comment]
I use them to create some functions related to time that I access in various javascript events in different external events. But I haven't touched them since the move to GD5 since the logic was already complete (for now).

**Comment by Wend1go** [comment]
@4ian Nice work on the Monaco integration. Its really a breeze to use :+1: 
Just one thing, could you make the code event collapsible? Maybe make the event a combination of a comment componnent and the editor componnent. The head is like a comment where the game developers can write a short summary about what the code in the event body does. Than add a triangle shaped button to collapse the head so that it doesn't take so much space. Otherwise one has to create a usual event and make the code event a sub-event of it. Code events tend to become pretty large which disturbs the readability of the events sheet.

Here is a mock up of what I have in mind:
image

**Comment by 4ian** [comment]
Yeah I think that with autocompletion it's surprisingly comfortable and fun to use. :) 
Btw, don't hesitate to flag/correct any missing function - in particular in extensions not everything is documented properly. Most of the objects/behaviors should not be complicated though.

I see what you need. I've created this card: https://trello.com/c/ubnDNbcX/137-allow-the-user-to-collapse-code-editor-of-javascript-events

I wonder though if we really need the comment at the top of the event? Could we keep using traditional comments/groups? And just have a button to collapse the whole thing?
(honest question, I don't know what would be better)

**Comment by Lizard-13** [comment]
You already have comments and groups to organize the events, I think it's ok as now, just need to be collapsible as Wend1go shows :)

**Comment by ddabrahim** [comment]
> I wonder though if we really need the comment at the top of the event?

I would have an even better idea XD
But first of all, let me say the editor truly looks and works amazing. It is going to be truly a great addition.
However, at times, especially when multiple editors are open, the events editor feels a bit slow. When scroll, sometimes I need to wait a moment to see the events which is a bit distracting. Even if we are going to use traditional comments and groups, JS events definitely need to be folded by default in my opinion.

Regarding my "even better idea"
How about to be able to expose certain values and variables to be able to change them, modify from the outside? When the JS event is collapsed, it would look and feel similar to an event but you can also think of it as a function that require some parameters.

The most simple way to select values to expose would be the public values, the ones highest in the scope. Just for the sake to expose values, we could force people to use a function inside each and every JS event, let say  Main. It is common among frameworks we need to use Initialize, Update, Draw , Main and other methods to organize our code. So it would be not totally alien to those who want to use JS.

So the idea is, all the variables declared outside the Main function would be public, and all public values would be exposed.

For example

mokup

And we could change the values on the top even if the event is collapsed.

Why would it be useful? Well, for one thing once we have the code done and all we do is experimenting with different values, it would be nice if we could just quickly change the values like in any other events. Just imagine you have 2-3-4 JS event and you wan to play the values for each. I think it would be useful to be able to have them collapsed and simply change the values exposed.
Also, it would allow us to create events that people could use even if they don't know JS. I know it is not a big deal to ask people to change a few values at the top, but it could look more friendly to people who do not code especially if we are about to make events that meant to be re-used by people in their own projects. 

I know I probably asking for a lot and it is definably not something I expect to come in the near future, but could be a nice addition in the distant future in my opinion.

Again, thanks a lot for this nice editor in GD :)

**Comment by 4ian** [comment]
> However, at times, especially when multiple editors are open, the events editor feels a bit slow.

Yeah, I guess the editor is not meant to be displayed a lot of time. It should be ok because events are virtualized (events not on the screen are not rendered) but can still have slowness when being displayed.

Concerning your idea, I see what you mean. It's actually kind of part of a more generic idea that I have to allow to use events or JS to declare extensions on the fly - like super powerful functions.

Note that for now, you can still at the beginning of your JavaScript code get the value of variables (`runtimeScene.getVariables().get...` or `runtimeScene.getGame().getVariables().get...` for global variables). Should be a first step to build reusable JavaScript code (along with the ability to pass objects too!)

**Pull request merged**
