### PR TITLE
Add device motion to sensor extension

### PR DESCRIPTION
**Pull request by Wend1go**
Note: Rotation is rarely available on mobile devices but it can be calculated from the orientation values.

### CODE REVIEW

**Comment by 4ian** [comment]
Looks nice :) A few questions:
* What is the unit of the acceleration? We should add this in the description of the parameters when asking for a value. Seems according to MDN that it's meters per second squared (m/s2).
* I can't help but think that it wasn't a good idea to have this "active" value that is a boolean, represented as a number - we're shortcutting JavaScript type system and create confusion. We should remove the expression allowing to get it and instead only expose a condition to check if it's active or not. In the more extreme case, if someone still reaaaally need to have the active as 1 or 0, he can make two events to set a variable to 1 or 0 (or anything else) according to the condition, no? What do you think?

Otherwise, the rest looks properly done :) Good job!

**Comment by Wend1go** [comment]
Good catch, I completely forgot the unit. ^^
I guess I'll remove the expression and keep the JavaScript function to retrieve the value (as boolean again).

**Comment by 4ian** [comment]
Sounds good :)

**Comment by Wend1go** [comment]
Ready to merge

**Pull request merged**
