### PR TITLE
Feature/anchor behavior

### PR DESCRIPTION
**Pull request by victorlevasseur**
This PR adds an **Anchor behavior** that can anchor the object's edges to the window's bounds.

### CODE REVIEW

**Comment by 4ian** [comment]
Ah that's awesome because yesterday I was thinking that this behavior was missing ^^
Will try it and probably do a port for HTML5 games.

**Comment by 4ian** [comment]
Any reason you've used m_* as a convention for member variable names? Looks good otherwise!

**Comment by victorlevasseur** [comment]
I'm just use to it. Feel free to change it.

**Comment by 4ian** [comment]
It's the class private part so that's all good :)

**Pull request merged**
