### PR TITLE
Feature/linkevent

### PR DESCRIPTION
**Pull request by victorlevasseur**
- New editor the the link event
 - Fix the bug with external events when the link only includes some events
 - Deprecate the "link only events from X to X position" feature (only available for "old" link events)
 - Link events can now include an events group (by name) of a layout/external events. If multiple group events have the same name, a warning is displayed and only the first one is included

Tested with simple testcases. But still need to be tested on bigger projects.

### CODE REVIEW

**Comment by 4ian** [comment]
Sorry did not have a chance to test it last week-end, but will do it before the end of the week!

**Comment by victorlevasseur** [comment]
Is it ok to merge ?

**Comment by 4ian** [comment]
Working good with an existing project that is heavily using links.
Just a question about this:
> Fix the bug with external events when the link only includes some events

What bug was this?

**Comment by victorlevasseur** [comment]
When GDevelop compiled the external events as a separated source file, the
line selection was ignored.

Le lun. 5 sept. 2016 à 23:09, Florian Rival <notifications@github.com> a
écrit :

**Comment by 4ian** [comment]
Ok! Well I'm going to merge this. Note that I'm using "Squash and merge" so that we have a single commit for this change + the bug fixes provided :)

**Pull request merged**
