### PR TITLE
fix scrolling issue

### PR DESCRIPTION
**Pull request by blurymind**
This pull fixes some scrolling issues on windows

### CODE REVIEW

**Comment by 4ian** [comment]
Oops sorry you get this error because I've updated `libGD.js`. Can you go to `newIDE/app/public` and remove `libGD.js`. Then relaunch `yarn start` or `npm run start` and it will download the updated version.
I have to think about a better thing to version libGD.js for other developers like you.

**Comment by blurymind** [comment]
@4ian thank you for explaining . I reverted the change and also made another commit that should fix 
https://github.com/4ian/GD/issues/497

**Comment by 4ian** [comment]
Thanks :) Can you run prettier on it? 
I'll have to double check that it's working on macOS :)

**Comment by blurymind** [comment]
@4ian oops sorry. Prettified now :)

I only changed the windows related code

**Pull request merged**
